if (navigator.serviceWorker) {
    navigator.serviceWorker.register('https://raw.githubusercontent.com/simpsons-generator/test/refs/heads/main/sw.js');
}

const words = [
  "Staffel 1, Folge 1: Es weihnachtet schwer",
  "Staffel 1, Folge 2: Bart wird ein Genie",
  "Staffel 1, Folge 3: Der Versager",
  "Staffel 1, Folge 4: Eine ganz normale Familie",
  "Staffel 1, Folge 5: Bart schlägt eine Schlacht",
  "Staffel 1, Folge 6: Lisa bläst Trübsal",
  "Staffel 1, Folge 7: Vorsicht, wilder Homer",
  "Staffel 1, Folge 8: Bart köpft Oberhaupt",
  "Staffel 1, Folge 9: Der schöne Jacques",
  "Staffel 1, Folge 10: Homer als Frauenheld",
  "Staffel 1, Folge 11: Tauschgeschäfte und Spione",
  "Staffel 1, Folge 12: Der Clown mit der Biedermaske",
  "Staffel 1, Folge 13: Der Babysitter ist los",
  "Staffel 2, Folge 1: Der Musterschüler",
  "Staffel 2, Folge 2: Karriere mit Köpfchen",
  "Staffel 2, Folge 3: Horror frei Haus",
  "Staffel 2, Folge 4: Frische Fische mit drei Augen",
  "Staffel 2, Folge 5: Das Maskottchen",
  "Staffel 2, Folge 6: Der Wettkampf",
  "Staffel 2, Folge 7: Bart bleibt hart",
  "Staffel 2, Folge 8: Der Teufelssprung",
  "Staffel 2, Folge 9: Das Fernsehen ist an allem schuld",
  "Staffel 2, Folge 10: Bart kommt unter die Räder",
  "Staffel 2, Folge 11: Die 24‑Stunden‑Frist",
  "Staffel 2, Folge 12: Wie alles begann",
  "Staffel 2, Folge 13: Das achte Gebot",
  "Staffel 2, Folge 14: Der Heiratskandidat",
  "Staffel 2, Folge 15: Ein Bruder für Homer",
  "Staffel 2, Folge 16: Betragen mangelhaft",
  "Staffel 2, Folge 17: Die Erbschaft",
  "Staffel 2, Folge 18: Marges Meisterwerk",
  "Staffel 2, Folge 19: Der Aushilfslehrer",
  "Staffel 2, Folge 20: Kampf dem Ehekrieg",
  "Staffel 2, Folge 21: Drei Freunde und ein Comic‑Heft",
  "Staffel 2, Folge 22: Der Lebensretter",
  "Staffel 3, Folge 1: Die Geburtstagsüberraschung",
  "Staffel 3, Folge 2: Einmal Washington und zurück",
  "Staffel 3, Folge 3: Ein Fluch auf Flanders",
  "Staffel 3, Folge 4: Verbrechen lohnt sich nicht",
  "Staffel 3, Folge 5: Der Ernstfall",
  "Staffel 3, Folge 6: Der Vater eines Clowns",
  "Staffel 3, Folge 7: Albträume",
  "Staffel 3, Folge 8: Lisas Pony",
  "Staffel 3, Folge 9: Das Seifenkistenrennen",
  "Staffel 3, Folge 10: Das Erfolgsrezept",
  "Staffel 3, Folge 11: Kraftwerk zu verkaufen",
  "Staffel 3, Folge 12: Blick zurück aufs Eheglück",
  "Staffel 3, Folge 13: Wer anderen einen Brunnen gräbt",
  "Staffel 3, Folge 14: Der Wettkönig",
  "Staffel 3, Folge 15: Wenn Mutter streikt",
  "Staffel 3, Folge 16: Die Kontaktanzeige",
  "Staffel 3, Folge 17: Der Wunderschläger",
  "Staffel 3, Folge 18: Der Eignungstest",
  "Staffel 3, Folge 19: Auf den Hund gekommen",
  "Staffel 3, Folge 20: Homer auf Abwegen",
  "Staffel 3, Folge 21: Bis dass der Tod euch scheidet",
  "Staffel 3, Folge 22: Der Fahrschüler",
  "Staffel 3, Folge 23: Liebe und Intrige",
  "Staffel 3, Folge 24: Der vermisste Halbbruder",
  "Staffel 4, Folge 1: Krise im Kamp Krusty",
  "Staffel 4, Folge 2: Bühne frei für Marge",
  "Staffel 4, Folge 3: Ein gotteslästerliches Leben",
  "Staffel 4, Folge 4: Lisa, die Schönheitskönigin",
  "Staffel 4, Folge 5: Bösartige Spiele",
  "Staffel 4, Folge 6: Bart wird bestraft",
  "Staffel 4, Folge 7: Marge muss jobben",
  "Staffel 4, Folge 8: Laura, die neue Nachbarin",
  "Staffel 4, Folge 9: Einmal als Schneekönig",
  "Staffel 4, Folge 10: Am Anfang war das Wort",
  "Staffel 4, Folge 11: Oh Schmerz, das Herz!",
  "Staffel 4, Folge 12: Homer kommt in Fahrt",
  "Staffel 4, Folge 13: Selma will ein Baby",
  "Staffel 4, Folge 14: Großer Bruder – kleiner Bruder",
  "Staffel 4, Folge 15: Ralph liebt Lisa",
  "Staffel 4, Folge 16: Keine Experimente",
  "Staffel 4, Folge 17: Prinzessin von Zahnstein",
  "Staffel 4, Folge 18: Nur ein Aprilscherz…",
  "Staffel 4, Folge 19: Wir vom Trickfilm",
  "Staffel 4, Folge 20: Das Schlangennest",
  "Staffel 4, Folge 21: Marge wird verhaftet",
  "Staffel 4, Folge 22: Krusty, der TV-Star",
  "Staffel 5, Folge 1: Homer und die Sangesbrüder",
  "Staffel 5, Folge 2: Am Kap der Angst",
  "Staffel 5, Folge 3: Homer an der Uni",
  "Staffel 5, Folge 4: Kampf um Bobo",
  "Staffel 5, Folge 5: Die Fahrt zur Hölle",
  "Staffel 5, Folge 6: Die rebellischen Weiber",
  "Staffel 5, Folge 7: Bart, das innere Ich",
  "Staffel 5, Folge 8: Auf Wildwasserfahrt",
  "Staffel 5, Folge 9: Homer liebt Mindy",
  "Staffel 5, Folge 10: Vom Teufel besessen",
  "Staffel 5, Folge 11: Die Springfield Bürgerwehr",
  "Staffel 5, Folge 12: Bart wird berühmt",
  "Staffel 5, Folge 13: Apu, der Inder",
  "Staffel 5, Folge 14: Lisa kontra Malibu Stacy",
  "Staffel 5, Folge 15: Homer, der Weltraumheld",
  "Staffel 5, Folge 16: Homie und Neddie",
  "Staffel 5, Folge 17: Bart gewinnt Elefant!",
  "Staffel 5, Folge 18: Burns Erbe",
  "Staffel 5, Folge 19: Freund oder Feind!",
  "Staffel 5, Folge 20: Bart packt aus",
  "Staffel 5, Folge 21: Liebhaber der Lady B.",
  "Staffel 5, Folge 22: Ehegeheimnisse",
  "Staffel 6, Folge 1: Ein grausiger Verdacht",
  "Staffel 6, Folge 2: Lisas Rivalin",
  "Staffel 6, Folge 3: Romantik ist überall",
  "Staffel 6, Folge 4: Der unheimliche Vergnügungspark",
  "Staffel 6, Folge 5: Tingeltangel-Bob",
  "Staffel 6, Folge 6: Furcht und Grauen ohne Ende",
  "Staffel 6, Folge 7: Barts Freundin",
  "Staffel 6, Folge 8: Lisa auf dem Eise",
  "Staffel 6, Folge 9: Die Babysitterin und das Biest",
  "Staffel 6, Folge 10: Grandpa gegen sexuelles Versagen",
  "Staffel 6, Folge 11: Angst vorm Fliegen",
  "Staffel 6, Folge 12: Homer der Auserwählte",
  "Staffel 6, Folge 13: Und Maggie macht drei",
  "Staffel 6, Folge 14: Barts Komet",
  "Staffel 6, Folge 15: Homie, der Clown",
  "Staffel 6, Folge 16: Bart gegen Australien",
  "Staffel 6, Folge 17: Homer gegen Patty und Selma",
  "Staffel 6, Folge 18: Springfield Film Festival",
  "Staffel 6, Folge 19: Lisas Hochzeit",
  "Staffel 6, Folge 20: 25 Windhundwelpen",
  "Staffel 6, Folge 21: Der Lehrerstreik",
  "Staffel 6, Folge 22: Zu Ehren von Murphy",
  "Staffel 6, Folge 23: Die Springfield Connection",
  "Staffel 6, Folge 24: Auf zum Zitronenbaum",
  "Staffel 6, Folge 25: Wer erschoss Mr. Burns? - Teil 1",
  "Staffel 7, Folge 1: Wer erschoss Mr. Burns? – Teil 2",
  "Staffel 7, Folge 2: Filmstar wider Willen",
"Staffel 7, Folge 3: Bei Simpsons stimmt was nicht!",
"Staffel 7, Folge 4: Bart verkauft seine Seele",
"Staffel 7, Folge 5: Lisa als Vegetarierin",
"Staffel 7, Folge 6: Die Panik-Amok-Horror-Show",
"Staffel 7, Folge 7: Der behinderte Homer",
"Staffel 7, Folge 8: Wer ist Mona Simpson?",
"Staffel 7, Folge 9: Tingeltangel-Bobs Rache",
"Staffel 7, Folge 10: Die 138. Episode, eine Sondervorstellung",
"Staffel 7, Folge 11: Das schwarze Schaf",
"Staffel 7, Folge 12: Homers Bowling-Mannschaft",
"Staffel 7, Folge 13: Die bösen Nachbarn",
"Staffel 7, Folge 14: Eine Klasse für sich",
"Staffel 7, Folge 15: Bart ist an allem schuld",
"Staffel 7, Folge 16: Das geheime Bekenntnis",
"Staffel 7, Folge 17: Butler bei Burns",
"Staffel 7, Folge 18: Wer erfand Itchy und Scratchy?",
"Staffel 7, Folge 19: Selma heiratet Hollywoodstar",
"Staffel 7, Folge 20: Die Reise nach Knoxville",
"Staffel 7, Folge 21: 22 Kurzfilme über Springfield",
"Staffel 7, Folge 22: Simpson und sein Enkel in „Die Schatzsuche“",
"Staffel 7, Folge 23: Volksabstimmung in Springfield",
"Staffel 7, Folge 24: Homer auf Tournee",
"Staffel 7, Folge 25: Ein Sommer für Lisa",
"Staffel 8, Folge 1: Hugo, kleine Wesen und Kang",
"Staffel 8, Folge 2: Das verlockende Angebot",
"Staffel 8, Folge 3: Auf in den Kampf!",
"Staffel 8, Folge 4: Mr. Burns’ Sohn Larry",
"Staffel 8, Folge 5: Der beliebte Amüsierbetrieb",
"Staffel 8, Folge 6: Scheide sich, wer kann",
"Staffel 8, Folge 7: Lisa will lieben",
"Staffel 8, Folge 8: Der total verrückte Ned",
"Staffel 8, Folge 9: Homers merkwürdiger Chili-Trip",
"Staffel 8, Folge 10: Die Akte Springfield",
"Staffel 8, Folge 11: Marge und das Brezelbacken",
"Staffel 8, Folge 12: Der Berg des Wahnsinns",
"Staffel 8, Folge 13: Das magische Kindermädchen",
"Staffel 8, Folge 14: Homer ist „Poochie, der Wunderhund“",
"Staffel 8, Folge 15: Homer und gewisse Ängste",
"Staffel 8, Folge 16: Die beiden hinterhältigen Brüder",
"Staffel 8, Folge 17: Babysitten – ein Albtraum",
"Staffel 8, Folge 18: Der mysteriöse Bier-Baron",
"Staffel 8, Folge 19: Wenn der Rektor mit der Lehrerin…",
"Staffel 8, Folge 20: Der tollste Hund der Welt",
"Staffel 8, Folge 21: Der alte Mann und Lisa",
"Staffel 8, Folge 22: Marge als Seelsorgerin",
"Staffel 8, Folge 23: Homer hatte einen Feind",
"Staffel 8, Folge 24: Ihre Lieblings-Fernsehfamilie",
"Staffel 8, Folge 25: Lisas geheimer Krieg",
"Staffel 9, Folge 1: Homer und New York",
"Staffel 9, Folge 2: Alles Schwindel",
"Staffel 9, Folge 3: Die Saxophon-Geschichte",
"Staffel 9, Folge 4: Neutronenkrieg und Halloween",
"Staffel 9, Folge 5: Homer und der Revolver",
"Staffel 9, Folge 6: Bart ist mein Superstar",
"Staffel 9, Folge 7: Hochzeit auf Indisch",
"Staffel 9, Folge 8: Der Tag der Abrechnung",
"Staffel 9, Folge 9: Todesfalle zu verkaufen",
"Staffel 9, Folge 10: Die Lieblings-Unglücksfamilie",
"Staffel 9, Folge 11: Und nun alle singen und tanzen",
"Staffel 9, Folge 12: Die armen Vagabunden",
"Staffel 9, Folge 13: In den Fängen einer Sekte",
"Staffel 9, Folge 14: Der blöde Uno-Club",
"Staffel 9, Folge 15: Krustys letzte Versuchung",
"Staffel 9, Folge 16: Eine Frau für Moe",
"Staffel 9, Folge 17: Vertrottelt Lisa?",
"Staffel 9, Folge 18: Der merkwürdige Schlüssel",
"Staffel 9, Folge 19: Homer geht zur Marine",
"Staffel 9, Folge 20: Die Trillion-Dollar-Note",
"Staffel 9, Folge 21: Die neuesten Kindernachrichten",
"Staffel 9, Folge 22: Die sich im Dreck wälzen",
"Staffel 9, Folge 23: König der Berge",
"Staffel 9, Folge 24: Die Kugel der Isis",
"Staffel 9, Folge 25: Die Gefahr, erwischt zu werden",
"Staffel 10, Folge 1: Ein jeder kriegt sein Fett",
"Staffel 10, Folge 2: Im Schatten des Genies",
"Staffel 10, Folge 3: Bart brütet etwas aus",
"Staffel 10, Folge 4: Das unheimliche Mord-Transplantat",
"Staffel 10, Folge 5: Kennst du berühmte Stars?",
"Staffel 10, Folge 6: Homer ist ein toller Hippie",
"Staffel 10, Folge 7: Die große Betrügerin",
"Staffel 10, Folge 8: Grandpa's Nieren explodieren",
"Staffel 10, Folge 9: Der unerschrockene Leibwächter",
"Staffel 10, Folge 10: Wir fahr’n nach… Vegas",
"Staffel 10, Folge 11: Allgemeine Ausgangssperre",
"Staffel 10, Folge 12: Nur für Spieler und Prominente",
"Staffel 10, Folge 13: Namen machen Leute",
"Staffel 10, Folge 14: Apu und Amor",
"Staffel 10, Folge 15: Marge Simpson im Anmarsch",
"Staffel 10, Folge 16: Es tut uns Leid, Lisa",
"Staffel 10, Folge 17: Das Geheimnis der Lastwagenfahrer",
"Staffel 10, Folge 18: Bibelstunde, einmal anders",
"Staffel 10, Folge 19: Überraschung für Springfield",
"Staffel 10, Folge 20: Seid nett zu alten Leuten",
"Staffel 10, Folge 21: Burns möchte geliebt werden",
"Staffel 10, Folge 22: Die Stadt der primitiven Langweiler",
"Staffel 10, Folge 23: Die japanische Horror-Spiel-Show",
"Staffel 11, Folge 1: Mit Mel Gibson in Hollywood",
"Staffel 11, Folge 2: Ist alles hin, nimm Focusin!",
"Staffel 11, Folge 3: Homer als Restaurantkritiker",
"Staffel 11, Folge 4: Ich weiß, was du getudel-tan hast",
"Staffel 11, Folge 5: Duell bei Sonnenaufgang",
"Staffel 11, Folge 6: Die Kurzzeit-Berühmtheit",
"Staffel 11, Folge 7: Schon mal an Kinder gedacht?",
"Staffel 11, Folge 8: Der Kampf um Marge",
"Staffel 11, Folge 9: Die böse Puppe Lustikus",
"Staffel 11, Folge 10: Lisa und ihre Jungs",
"Staffel 11, Folge 11: Bart hat die Kraft",
"Staffel 11, Folge 12: Wenn ich einmal reich wär",
"Staffel 11, Folge 13: Ein Pferd für die Familie",
"Staffel 11, Folge 14: Ned Flanders: Wieder allein",
"Staffel 11, Folge 15: Der beste Missionar aller Zeiten",
"Staffel 11, Folge 16: Moe mit den zwei Gesichtern",
"Staffel 11, Folge 17: Barts Blick in die Zukunft",
"Staffel 11, Folge 18: Barneys Hubschrauber-Flugstunde",
"Staffel 11, Folge 19: Kill den Alligator und dann…",
"Staffel 11, Folge 20: Sie wollte schon immer Tänzerin werden",
"Staffel 11, Folge 21: Wird Marge verrückt gemacht?",
"Staffel 11, Folge 22: Hinter den Lachern",
"Staffel 12, Folge 1: D-D-Der G-G-Geister D-D-Dad",
"Staffel 12, Folge 2: Die Geschichte der zwei Springfields",
"Staffel 12, Folge 3: O mein Clown Papa",
"Staffel 12, Folge 4: Lisa als Baumliebhaberin",
"Staffel 12, Folge 5: Homer und das Geschenk der Würde",
"Staffel 12, Folge 6: Mr. X und der Website-Schund",
"Staffel 12, Folge 7: Das große Geldabzocken",
"Staffel 12, Folge 8: Rektor Skinners Gespür für Schnee",
"Staffel 12, Folge 9: Der berüchtigte Kleinhirn-Malstift",
"Staffel 12, Folge 10: Jack und der Rückgratzylinder",
"Staffel 12, Folge 11: Die schlechteste Episode überhaupt",
"Staffel 12, Folge 12: Tennis mit Venus",
"Staffel 12, Folge 13: Hallo, du kleiner Hypnose-Mörder",
"Staffel 12, Folge 14: Die sensationelle Pop-Gruppe",
"Staffel 12, Folge 15: Der hungrige, hungrige Homer",
"Staffel 12, Folge 16: Lisa knackt den Rowdy-Code",
"Staffel 12, Folge 17: Die Sippe auf Safari",
"Staffel 12, Folge 18: Trilogie derselben Geschichte",
"Staffel 12, Folge 19: Wunder gibt es immer wieder",
"Staffel 12, Folge 20: Der Schwindler und seine Kinder",
"Staffel 12, Folge 21: Drei unglaubliche Geschichten",
"Staffel 13, Folge 1: Hex and the City",
"Staffel 13, Folge 2: Ich bin bei dir, mein Sohn",
"Staffel 13, Folge 3: Homer und Moe St. Cool",
"Staffel 13, Folge 4: Gloria – die wahre Liebe",
"Staffel 13, Folge 5: Aus dunklen Zeiten",
"Staffel 13, Folge 6: Allein ihr fehlt der Glaube",
"Staffel 13, Folge 7: Familienkrawall – Maggie verhaftet",
"Staffel 13, Folge 8: Die süßsaure Marge",
"Staffel 13, Folge 9: Sein Kiefer ist verdrahtet",
"Staffel 13, Folge 10: Ein halbanständiger Antrag",
"Staffel 13, Folge 11: Nach Kanada der Liebe wegen",
"Staffel 13, Folge 12: Bart und sein Westernheld",
"Staffel 13, Folge 13: Abraham und Zelda",
"Staffel 13, Folge 14: Drei uralte Geschichten",
"Staffel 13, Folge 15: Das ist alles nur Lisas Schuld",
"Staffel 13, Folge 16: Homer einmal ganz woanders",
"Staffel 13, Folge 17: Forrest Plump und die Clip Show",
"Staffel 13, Folge 18: Der rasende Wüterich",
"Staffel 13, Folge 19: Die Apu und Manjula Krise",
"Staffel 13, Folge 20: L.S. Meisterin des Doppellebens",
"Staffel 13, Folge 21: Am Anfang war die Schreiraupe",
"Staffel 13, Folge 22: Sicherheitsdienst „SpringShield“",
"Staffel 14, Folge 1: Schickt die Klone rein",
"Staffel 14, Folge 2: It’s only Rock’n’Roll",
"Staffel 14, Folge 3: Klassenkampf",
"Staffel 14, Folge 4: Marge – oben ohne",
"Staffel 14, Folge 5: Der Videobeichtstuhl",
"Staffel 14, Folge 6: Und der Mörder ist…",
"Staffel 14, Folge 7: Lehrerin des Jahres",
"Staffel 14, Folge 8: Der Vater, der zu wenig wusste",
"Staffel 14, Folge 9: Die starken Arme der Marge",
"Staffel 14, Folge 10: Ein kleines Gebet",
"Staffel 14, Folge 11: Bart, das Werbebaby",
"Staffel 14, Folge 12: Buchstabe für Buchstabe",
"Staffel 14, Folge 13: Ein Stern wird neugeboren",
"Staffel 14, Folge 14: Krusty im Kongress",
"Staffel 14, Folge 15: Mr. Burns wird entlassen",
"Staffel 14, Folge 16: Nacht über Springfield",
"Staffel 14, Folge 17: Homer auf Irrwegen",
"Staffel 14, Folge 18: Auf der Familienranch",
"Staffel 14, Folge 19: Die Helden von Springfield",
"Staffel 14, Folge 20: Stresserella über alles",
"Staffel 14, Folge 21: Auf dem Kriegspfad",
"Staffel 14, Folge 22: Moe Baby Blues",
"Staffel 15, Folge 1: Todesgrüße aus Springfield",
"Staffel 15, Folge 2: Wiedersehen nach Jahren",
"Staffel 15, Folge 3: Die Perlen-Präsidentin",
"Staffel 15, Folge 4: Die Queen ist nicht erfreut!",
"Staffel 15, Folge 5: Der Dicke und der Bär",
"Staffel 15, Folge 6: Krustys Bar Mitzvah",
"Staffel 15, Folge 7: Eine Simpsons-Weihnachtsgeschichte",
"Staffel 15, Folge 8: Marge gegen Singles, Senioren, kinderlose Paare, Teenager und Schwule",
"Staffel 15, Folge 9: Häuptling KnockaHomer",
"Staffel 15, Folge 10: Fantasien einer durchgeknallten Hausfrau",
"Staffel 15, Folge 11: Geschichtsstunde mit Marge",
"Staffel 15, Folge 12: Milhouse lebt hier nicht mehr",
"Staffel 15, Folge 13: Klug & Klüger",
"Staffel 15, Folge 14: Rat mal, wer zum Essen kommt",
"Staffel 15, Folge 15: Marge im Suff",
"Staffel 15, Folge 16: Die Verurteilten",
"Staffel 15, Folge 17: Hochzeit auf Klingonisch",
"Staffel 15, Folge 18: Auf der Flucht",
"Staffel 15, Folge 19: Der Tortenmann schlägt zurück",
"Staffel 15, Folge 20: Die erste Liebe",
"Staffel 15, Folge 21: Geächtet",
"Staffel 15, Folge 22: Der große Nachrichtenschwindel",
"Staffel 16, Folge 1: Vier Enthauptungen und ein Todesfall",
"Staffel 16, Folge 2: Die geheime Zutat",
"Staffel 16, Folge 3: Der Feind in meinem Bett",
"Staffel 16, Folge 4: Marges alte Freundin",
"Staffel 16, Folge 5: Dicker Mann und kleiner Junge",
"Staffel 16, Folge 6: Nach Kanada der Pillen wegen",
"Staffel 16, Folge 7: Moes Taverne",
"Staffel 16, Folge 8: Homer und die Halbzeit-Show",
"Staffel 16, Folge 9: Pranksta Rap",
"Staffel 16, Folge 10: Drum prüfe, wer sich ewig bindet",
"Staffel 16, Folge 11: Die böse Hexe des Westens",
"Staffel 16, Folge 12: Der lächelnde Buddha",
"Staffel 16, Folge 13: Homer mobil",
"Staffel 16, Folge 14: Homer, die Ratte",
"Staffel 16, Folge 15: Future-Drama",
"Staffel 16, Folge 16: Der eingebildete Dachdecker",
"Staffel 16, Folge 17: Das große Fressen",
"Staffel 16, Folge 18: Lisa Simpson: Superstar",
"Staffel 16, Folge 19: Das jüngste Gericht",
"Staffel 16, Folge 20: Schau heimwärts, Flanders",
"Staffel 16, Folge 21: Der Vater, der Sohn und der heilige Gaststar",
"Staffel 17, Folge 1: Es lebe die Seekuh!",
"Staffel 17, Folge 2: Angst essen Seele auf",
"Staffel 17, Folge 3: Milhouse aus Sand und Nebel",
"Staffel 17, Folge 4: B.I.: Bartificial Intelligence",
"Staffel 17, Folge 5: Mamas kleiner Liebling",
"Staffel 17, Folge 6: Der Sicherheitssalamander",
"Staffel 17, Folge 7: Marge und der Frauen-Club",
"Staffel 17, Folge 8: Der italienische Bob",
"Staffel 17, Folge 9: Simpsons Weihnachtsgeschichten",
"Staffel 17, Folge 10: Wer ist Homers Vater?",
"Staffel 17, Folge 11: Straße der Verdammten",
"Staffel 17, Folge 12: Ein perfekter Gentleman",
"Staffel 17, Folge 13: Die scheinbar unendliche Geschichte",
"Staffel 17, Folge 14: Bart hat zwei Mütter",
"Staffel 17, Folge 15: Frauentausch",
"Staffel 17, Folge 16: Corrida de Toro",
"Staffel 17, Folge 17: Kiss Kiss Bang Bangalore",
"Staffel 17, Folge 18: Drei nasse Geschichten",
"Staffel 17, Folge 19: Gleichung mit einem Unbekannten",
"Staffel 17, Folge 20: Selig sind die Unwissenden",
"Staffel 17, Folge 21: Gott gegen Lisa Simpson",
"Staffel 17, Folge 22: Homerun für die Liebe",
"Staffel 18, Folge 1: Der Koch, der Mafioso, die Frau und ihr Homer",
"Staffel 18, Folge 2: Jazzy and the Pussycats",
"Staffel 18, Folge 3: Homer, hol den Hammer raus",
"Staffel 18, Folge 4: Krieg der Welten",
"Staffel 18, Folge 5: G.I. Homer",
"Staffel 18, Folge 6: Das literarische Duett",
"Staffel 18, Folge 7: Kunst am Stiel",
"Staffel 18, Folge 8: Beste Freunde",
"Staffel 18, Folge 9: Kill Gil – Vol. 1 & 2",
"Staffel 18, Folge 10: Der perfekte Sturm",
"Staffel 18, Folge 11: Rache ist dreimal süß",
"Staffel 18, Folge 12: Mit gespaltener Zunge",
"Staffel 18, Folge 13: Springfield wird erwachsen",
"Staffel 18, Folge 14: Selig sind die Dummen",
"Staffel 18, Folge 15: Ein unmögliches Paar",
"Staffel 18, Folge 16: Homerazzi",
"Staffel 18, Folge 17: Marge Online",
"Staffel 18, Folge 18: Ballverlust",
"Staffel 18, Folge 19: Brand und Beute",
"Staffel 18, Folge 20: Stop! Oder mein Hund schießt",
"Staffel 18, Folge 21: 24 Minuten",
"Staffel 18, Folge 22: Das böse Wort",
"Staffel 19, Folge 1: Die unglaubliche Reise in einem verrückten Privatflugzeug",
"Staffel 19, Folge 2: Homerotti",
"Staffel 19, Folge 3: Abgeschleppt!",
"Staffel 19, Folge 4: Ich will nicht wissen, warum der gefangene Vogel singt",
"Staffel 19, Folge 5: Nach Hause telefonieren",
"Staffel 19, Folge 6: Kleiner Waise Milhouse",
"Staffel 19, Folge 7: Szenen einer Ehe",
"Staffel 19, Folge 8: Begräbnis für einen Feind",
"Staffel 19, Folge 9: Vergiss-Marge-Nicht",
"Staffel 19, Folge 10: Hello, Mr. President",
"Staffel 19, Folge 11: Die wilden 90er",
"Staffel 19, Folge 12: Die Liebe in Springfield",
"Staffel 19, Folge 13: Debarted – Unter Ratten",
"Staffel 19, Folge 14: Bei Absturz Mord",
"Staffel 19, Folge 15: Schall und Rauch",
"Staffel 19, Folge 16: Die Sünden der Väter",
"Staffel 19, Folge 17: Rinderwahn",
"Staffel 19, Folge 18: Down by Lisa",
"Staffel 19, Folge 19: Lebewohl, Mona",
"Staffel 19, Folge 20: Alles über Lisa",
"Staffel 20, Folge 1: Kuchen, Kopfgeld und Kautionen",
"Staffel 20, Folge 2: Jäger des verlorenen Handys",
"Staffel 20, Folge 3: Gemischtes Doppel",
"Staffel 20, Folge 4: Der Tod kommt dreimal",
"Staffel 20, Folge 5: Gefährliche Kurven",
"Staffel 20, Folge 6: Das Kreuz mit den Worträtseln",
"Staffel 20, Folge 7: Bin runterladen",
"Staffel 20, Folge 8: Ja, diese Biene, die ich meine, die heißt Monty",
"Staffel 20, Folge 9: Die Chroniken von Equalia",
"Staffel 20, Folge 10: Quatsch mit Soße",
"Staffel 20, Folge 11: Beim Testen nichts Neues",
"Staffel 20, Folge 12: Liebe deinen Nachbarn",
"Staffel 20, Folge 13: Auf der Jagd nach dem Juwel von Springfield",
"Staffel 20, Folge 14: Im Namen des Großvaters",
"Staffel 20, Folge 15: Hochzeit kommt vor dem Fall",
"Staffel 20, Folge 16: Große, kleine Liebe",
"Staffel 20, Folge 17: Verliebt und zugedröhnt",
"Staffel 20, Folge 18: Der Papa wird’s nicht richten",
"Staffel 20, Folge 19: Auf nach Waverly Hills",
"Staffel 20, Folge 20: Vier Powerfrauen und eine Maniküre",
"Staffel 20, Folge 21: Es war einmal in Homerika",
"Staffel 21, Folge 1: Everyman begins",
"Staffel 21, Folge 2: Die Antwort",
"Staffel 21, Folge 3: Marge macht mobil",
"Staffel 21, Folge 4: Mörder, Zombies und Musik",
"Staffel 21, Folge 5: Der Teufel trägt Nada",
"Staffel 21, Folge 6: L wie Looser",
"Staffel 21, Folge 7: Die Hexen von Springfield",
"Staffel 21, Folge 8: Lebe lieber unbebrudert",
"Staffel 21, Folge 9: Donnerstags bei Abe",
"Staffel 21, Folge 10: Es war einmal in Springfield",
"Staffel 21, Folge 11: Million Dollar Homie",
"Staffel 21, Folge 12: Curling Queen",
"Staffel 21, Folge 13: Die Farbe Gelb",
"Staffel 21, Folge 14: Grand Theft U-Bahn",
"Staffel 21, Folge 15: Der gestohlene Kuss",
"Staffel 21, Folge 16: Simpson und Gomorrha",
"Staffel 21, Folge 17: Jailhouse Blues",
"Staffel 21, Folge 18: Chief der Herzen",
"Staffel 21, Folge 19: Walverwandtschaft",
"Staffel 21, Folge 20: Nedtropolis",
"Staffel 21, Folge 21: Der weinende Dritte",
"Staffel 21, Folge 22: Bob von nebenan",
"Staffel 21, Folge 23: Richte deinen Nächsten",
"Staffel 22, Folge 1: Grundschul-Musical",
"Staffel 22, Folge 2: Auf diese Lisa können sie bauen",
"Staffel 22, Folge 3: The Lisa Series",
"Staffel 22, Folge 4: Blut und Spiele",
"Staffel 22, Folge 5: Die Lisa-Studie",
"Staffel 22, Folge 6: Das Wunder von Burns",
"Staffel 22, Folge 7: Eine Taube macht noch keinen Sommer",
"Staffel 22, Folge 8: The Fight Before Christmas",
"Staffel 22, Folge 9: Donnie Fatso",
"Staffel 22, Folge 10: Im Zeichen des Schwertes",
"Staffel 22, Folge 11: Moeback Mountain",
"Staffel 22, Folge 12: Wenn der Homer mit dem Sohne",
"Staffel 22, Folge 13: Die Farbe Grau",
"Staffel 22, Folge 14: Wütender Dad – Der Film",
"Staffel 22, Folge 15: Skorpione wie wir",
"Staffel 22, Folge 16: Ein Sommernachtstrip",
"Staffel 22, Folge 17: Denn sie wissen nicht, wen sie würgen",
"Staffel 22, Folge 18: Die große Simpsina",
"Staffel 22, Folge 19: Die Mafiosi-Braut",
"Staffel 22, Folge 20: Homer mit den Fingerhänden",
"Staffel 22, Folge 21: 500 Schlüssel",
"Staffel 22, Folge 22: Nedna",
"Staffel 23, Folge 1: Homer Impossible",
"Staffel 23, Folge 2: Teddy-Power",
"Staffel 23, Folge 3: Spider-Killer-Avatar-Man",
"Staffel 23, Folge 4: Das Ding, das aus Ohio kam",
"Staffel 23, Folge 5: FoodFellas",
"Staffel 23, Folge 6: Homers Sieben",
"Staffel 23, Folge 7: Der Mann im blauen Flanell",
"Staffel 23, Folge 8: Agentin mit Schmerz",
"Staffel 23, Folge 9: Weihnachten – Die nächste Generation",
"Staffel 23, Folge 10: Im Rausch der Macht",
"Staffel 23, Folge 11: Freundschaftsanfrage von Lisa",
"Staffel 23, Folge 12: Der Stoff, aus dem die Träume sind",
"Staffel 23, Folge 13: Unter dem Maulbeerbaum",
"Staffel 23, Folge 14: Fern der Heimat",
"Staffel 23, Folge 15: El Barto",
"Staffel 23, Folge 16: How I Wet Your Mother",
"Staffel 23, Folge 17: Mein Freund, der Roboter",
"Staffel 23, Folge 18: Gestrandet",
"Staffel 23, Folge 19: Im Zeichen der Kreuzfahrt",
"Staffel 23, Folge 20: Der Spion, der mich anlernte",
"Staffel 23, Folge 21: Schlaflos mit Nedna",
"Staffel 23, Folge 22: Lisa wird gaga",
"Staffel 24, Folge 1: Moonshine River",
"Staffel 24, Folge 2: Die unheimlich verteufelte Zeitreise durch das schwarze Loch",
"Staffel 24, Folge 3: Homers vergessene Kinder",
"Staffel 24, Folge 4: Grampa auf Abwegen",
"Staffel 24, Folge 5: Goodsimpsons",
"Staffel 24, Folge 6: Mein Freund, der Wunderbaum",
"Staffel 24, Folge 7: Coole Aussichten",
"Staffel 24, Folge 8: Wem der Bongo schlägt",
"Staffel 24, Folge 9: Homergeddon",
"Staffel 24, Folge 10: Das Bart-Ultimatum",
"Staffel 24, Folge 11: Stille Wasser sind adoptiv",
"Staffel 24, Folge 12: Verrückt nach Mary",
"Staffel 24, Folge 13: Eine Glatze macht noch keinen Kirk",
"Staffel 24, Folge 14: Der glamouröse Godfrey",
"Staffel 24, Folge 15: Blauauge sei wachsam",
"Staffel 24, Folge 16: Burns Begins",
"Staffel 24, Folge 17: Was animierte Frauen wollen",
"Staffel 24, Folge 18: Apokalypse Springfield",
"Staffel 24, Folge 19: Whiskey Business",
"Staffel 24, Folge 20: Der fabelhafte Faker Boy",
"Staffel 24, Folge 21: Die Legende von Carl",
"Staffel 24, Folge 22: Glück auf Schienen",
"Staffel 25, Folge 1: Homerland",
"Staffel 25, Folge 2: Freaks in der Manege",
"Staffel 25, Folge 3: Nichts bereuen",
"Staffel 25, Folge 4: YOLO",
"Staffel 25, Folge 5: Homer Junior",
"Staffel 25, Folge 6: Silly Simpsony",
"Staffel 25, Folge 7: Global Clowning",
"Staffel 25, Folge 8: White Christmas Blues",
"Staffel 25, Folge 9: Cinema Piratiso",
"Staffel 25, Folge 10: Manga Love Story",
"Staffel 25, Folge 11: Enter the Matrix",
"Staffel 25, Folge 12: Durch Diggs und dünn",
"Staffel 25, Folge 13: Der Herr der Gene",
"Staffel 25, Folge 14: Besuch der alten Herren",
"Staffel 25, Folge 15: Malen nach Bezahlen",
"Staffel 25, Folge 16: Homer, die Pfeife",
"Staffel 25, Folge 17: Luca$",
"Staffel 25, Folge 18: Vorwärts in die Zukunft",
"Staffel 25, Folge 19: Ihr Kinderlein kommet",
"Staffel 25, Folge 20: Auf dänische Steine können Sie bauen",
"Staffel 25, Folge 21: Ziemlich beste Freundin",
"Staffel 25, Folge 22: Feigheit kommt vor dem Fall",
"Staffel 26, Folge 1: Der traurige Clown",
"Staffel 26, Folge 2: Wir kentern alle in einem Boot",
"Staffel 26, Folge 3: Super Franchise Me",
"Staffel 26, Folge 4: Hölle, Tod und Geister",
"Staffel 26, Folge 5: Fracking, Freude, Eierkuchen",
"Staffel 26, Folge 6: Simpsorama",
"Staffel 26, Folge 7: Fackeln im Sandsturm",
"Staffel 26, Folge 8: Covercraft",
"Staffel 26, Folge 9: Der Weingeist der Weihnacht",
"Staffel 26, Folge 10: Der Mann, der als Dinner kam",
"Staffel 26, Folge 11: Barts neuer Freund",
"Staffel 26, Folge 12: Der Musk, der vom Himmel fiel",
"Staffel 26, Folge 13: Fett ist fabelhaft",
"Staffel 26, Folge 14: Driving Miss Marge",
"Staffel 26, Folge 15: Ein Herz und eine Krone",
"Staffel 26, Folge 16: Sky-Polizei",
"Staffel 26, Folge 17: Warten auf Duffman",
"Staffel 26, Folge 18: Marge will's wissen",
"Staffel 26, Folge 19: Fight Club",
"Staffel 26, Folge 20: Air Force Grampa",
"Staffel 26, Folge 21: Das Schweigen der Rowdys",
"Staffel 26, Folge 22: Eins, zwei oder drei",
"Staffel 27, Folge 1: Traumwelten",
"Staffel 27, Folge 2: Grilling Homer",
"Staffel 27, Folge 3: Grauer Dunst",
"Staffel 27, Folge 4: Horror-Halloween",
"Staffel 27, Folge 5: Killer und Zilla",
"Staffel 27, Folge 6: Freundin mit gewissen Vorzügen",
"Staffel 27, Folge 7: Lisa on Broadway",
"Staffel 27, Folge 8: Wege zum Ruhm",
"Staffel 27, Folge 9: Barthood",
"Staffel 27, Folge 10: Conrad",
"Staffel 27, Folge 11: Die Milch macht’s",
"Staffel 27, Folge 12: Apucalypse Now",
"Staffel 27, Folge 13: Liebe liegt in der N2-O2-Ar-CO2-Ne-He-CH4",
"Staffel 27, Folge 14: Die Frau im Schrank",
"Staffel 27, Folge 15: Lisa und das liebe Vieh",
"Staffel 27, Folge 16: Die Marge-Ianer",
"Staffel 27, Folge 17: Ein Käfig voller Smithers",
"Staffel 27, Folge 18: Die Jazz-Krise",
"Staffel 27, Folge 19: Fland Canyon",
"Staffel 27, Folge 20: Der Kurier, der mich liebte",
"Staffel 27, Folge 21: Simprovisation",
"Staffel 27, Folge 22: Orange is the New Yellow",
"Staffel 28, Folge 1: Springfield aus der Asche",
"Staffel 28, Folge 2: Die virtuelle Familie",
"Staffel 28, Folge 3: Stadt ohne Gnade",
"Staffel 28, Folge 4: Trocken, tot und tödlich",
"Staffel 28, Folge 5: Fake-News",
"Staffel 28, Folge 6: Mein peinlicher Freund",
"Staffel 28, Folge 7: Fidel Grampa",
"Staffel 28, Folge 8: Affenhilfe",
"Staffel 28, Folge 9: Mr. und Mrs. Smithers",
"Staffel 28, Folge 10: Krustliche Weihnachten",
"Staffel 28, Folge 11: Ein Schweinchen namens Propper",
"Staffel 28, Folge 12: Der große Phatsby (1): Der Verrat",
"Staffel 28, Folge 13: Der große Phatsby (2): Die Rache",
"Staffel 28, Folge 14: Fettscarraldo",
"Staffel 28, Folge 15: Homersche Eröffnung",
"Staffel 28, Folge 16: Krise nach Kamp Krusty",
"Staffel 28, Folge 17: 22 für 30",
"Staffel 28, Folge 18: Der Uhr-Großvater",
"Staffel 28, Folge 19: Homer Academy",
"Staffel 28, Folge 20: Auf der Suche nach Mr. Goodbart",
"Staffel 28, Folge 21: Moho House",
"Staffel 28, Folge 22: Dogtown",
"Staffel 29, Folge 1: Die Sklavsons",
"Staffel 29, Folge 2: Sad Girl",
"Staffel 29, Folge 3: Talent mit Pfiff",
"Staffel 29, Folge 4: Der Exorzismus von Maggie Simpson",
"Staffel 29, Folge 5: Grampa ist ganz Ohr",
"Staffel 29, Folge 6: Blau im Amt",
"Staffel 29, Folge 7: Die Pin Pals",
"Staffel 29, Folge 8: Lisa legt los",
"Staffel 29, Folge 9: Gone Boy",
"Staffel 29, Folge 10: Ha-Ha Land",
"Staffel 29, Folge 11: Arche Monty",
"Staffel 29, Folge 12: Manacek",
"Staffel 29, Folge 13: Doppeltes Einkommen, kinderlos",
"Staffel 29, Folge 14: Krusty macht ernst",
"Staffel 29, Folge 15: Politisch unkorrekt",
"Staffel 29, Folge 16: Der Matratzenkönig",
"Staffel 29, Folge 17: Lisa hat den Blues",
"Staffel 29, Folge 18: Rezeptfrei",
"Staffel 29, Folge 19: Links liegen gelassen",
"Staffel 29, Folge 20: Dänisches Krankenlager",
"Staffel 29, Folge 21: Der Tod steht ihm gut",
"Staffel 30, Folge 1: Bart ist nicht tot",
"Staffel 30, Folge 2: Heartbreak Hotel",
"Staffel 30, Folge 3: Himmlische Geschichten",
"Staffel 30, Folge 4: Planet im Nebel",
"Staffel 30, Folge 5: Passives Fahren",
"Staffel 30, Folge 6: Keine Frau für Moe",
"Staffel 30, Folge 7: Genderama",
"Staffel 30, Folge 8: Krusty, der Clown",
"Staffel 30, Folge 9: Daddicus Finch",
"Staffel 30, Folge 10: Weihnachten in Florida",
"Staffel 30, Folge 11: Plastiktrauma",
"Staffel 30, Folge 12: Das Mädchen im Bus",
"Staffel 30, Folge 13: Fett's Dance",
"Staffel 30, Folge 14: Projekt Weltraumsand",
"Staffel 30, Folge 15: Der Prozess",
"Staffel 30, Folge 16: Mission Simpossible",
"Staffel 30, Folge 17: Friss meine Sports",
"Staffel 30, Folge 18: Bart gegen Itchy & Scratchy",
"Staffel 30, Folge 19: Harmonie vs. Philharmonie",
"Staffel 30, Folge 20: Oklahoma",
"Staffel 30, Folge 21: Oh, Kanada",
"Staffel 30, Folge 22: Kriminalakte Springfield",
"Staffel 30, Folge 23: Kristallblaue Versuchung",
 "Staffel 31, Folge 1: Der Winter unseres monetarisierten Vergnügens",
  "Staffel 31, Folge 2: Der Mentor",
  "Staffel 31, Folge 3: San Castellaneta",
  "Staffel 31, Folge 4: Episode 666",
  "Staffel 31, Folge 5: Gorilla Ahoi!",
  "Staffel 31, Folge 6: Stammesfehde",
  "Staffel 31, Folge 7: La Pura Vida",
  "Staffel 31, Folge 8: Das perfekte Dinner",
  "Staffel 31, Folge 9: Mein Todd, mein Todd, warum hast du mich verlassen?",
  "Staffel 31, Folge 10: Süßer die Glocken nie tingeln",
  "Staffel 31, Folge 11: Bitte lächeln!",
  "Staffel 31, Folge 12: Mensch gegen Maschine",
  "Staffel 31, Folge 13: Frinkcoin",
  "Staffel 31, Folge 14: Spoiler Boy",
  "Staffel 31, Folge 15: Bildschirmlos",
  "Staffel 31, Folge 16: Die Bart Verschwörung",
  "Staffel 31, Folge 17: Highway to Well",
  "Staffel 31, Folge 18: Maggies erste Liebe",
  "Staffel 31, Folge 19: Krieg der Priester (1)",
  "Staffel 31, Folge 20: Krieg der Priester (2)",
  "Staffel 31, Folge 21: Erbarmungslos",
  "Staffel 31, Folge 22: Der Weg des Hundes",
  "Staffel 32, Folge 1: Undercover Burns",
  "Staffel 32, Folge 2: Bartigula",
  "Staffel 32, Folge 3: Kunst ist, wenn man trotzdem lacht",
  "Staffel 32, Folge 4: Saures oder Zeitschleife",
  "Staffel 32, Folge 5: Das verflixte 7. Bier",
  "Staffel 32, Folge 6: Podcast News",
  "Staffel 32, Folge 7: Drei gescheiterte Träume",
  "Staffel 32, Folge 8: Der lange Weg nach Cincinnati",
  "Staffel 32, Folge 9: Lisa tut es nicht leid",
  "Staffel 32, Folge 10: Sommer-Weihnacht in Springfield",
  "Staffel 32, Folge 11: Vorwärts in die Vergangenheit",
  "Staffel 32, Folge 12: Das Tagebuch der Mrs. K",
  "Staffel 32, Folge 13: C.R.E.A.M.",
  "Staffel 32, Folge 14: Cletus 4 Ever",
  "Staffel 32, Folge 15: Die Rückkehr der Pizza-Bots",
  "Staffel 32, Folge 16: Es ist ein Todd entsprungen",
  "Staffel 32, Folge 17: Die weiblichen Verdächtigen",
  "Staffel 32, Folge 18: Burger Kings",
  "Staffel 32, Folge 19: Panik in den Straßen von Springfield",
  "Staffel 32, Folge 20: Die Königin der Staaten",
  "Staffel 32, Folge 21: Codename G.R.A.M.P.A.",
  "Staffel 32, Folge 22: Moe Szyslak und das Königreich des Kristallschädels",
  "Staffel 33, Folge 1: Millennium-Bug - Das Musical",
  "Staffel 33, Folge 2: Bart ist im Knast",
  "Staffel 33, Folge 3: A Nightmare on Elm Tree",
  "Staffel 33, Folge 4: Moe-Zart",
  "Staffel 33, Folge 5: Bauchgefühl",
  "Staffel 33, Folge 6: A Serious Flanders (Teil 1)",
  "Staffel 33, Folge 7: A Serious Flanders (Teil 2)",
  "Staffel 33, Folge 8: Porträt eines jungen Lakaien in Flammen",
  "Staffel 33, Folge 9: Muttertag",
  "Staffel 33, Folge 10: Der Pate",
  "Staffel 33, Folge 11: Football-Mom",
  "Staffel 33, Folge 12: Survivor",
  "Staffel 33, Folge 13: Boyz N the Highlands",
  "Staffel 33, Folge 14: Das Institut",
  "Staffel 33, Folge 15: Bartman One",
  "Staffel 33, Folge 16: Ich bin Smartacus!",
  "Staffel 33, Folge 17: Ausgeblutet",
  "Staffel 33, Folge 18: Ein kurzer Film über die Liebe",
  "Staffel 33, Folge 19: Es braut sich was zusammen",
  "Staffel 33, Folge 20: Marge, das Monster",
  "Staffel 33, Folge 21: Fleisch ist Mord",
  "Staffel 33, Folge 22: Armenhaus-Rock",
  "Staffel 34, Folge 1: Die Schildkrötenverschwörung",
  "Staffel 34, Folge 2: Eine sportliche Affäre",
  "Staffel 34, Folge 3: Alles Lüge",
  "Staffel 34, Folge 4: Daytime-Marge",
  "Staffel 34, Folge 5: Nicht Es",
  "Staffel 34, Folge 6: Simpsonsworld",
  "Staffel 34, Folge 7: Duff-Dad",
  "Staffel 34, Folge 8: Der Stiefbruder",
  "Staffel 34, Folge 9: Nelson und Lisa",
  "Staffel 34, Folge 10: Das Skinner-Bart-System",
  "Staffel 34, Folge 11: Top Goon",
  "Staffel 34, Folge 12: Mein Leben als Vlog",
  "Staffel 34, Folge 13: The Many Saints of Springfield",
  "Staffel 34, Folge 14: Carl Carlson reitet wieder",
  "Staffel 34, Folge 15: Bartlos",
  "Staffel 34, Folge 16: Wut im Bauch",
  "Staffel 34, Folge 17: Queenpin",
  "Staffel 34, Folge 18: Fan-ilien-Fehde",
  "Staffel 34, Folge 19: Blue-Washing",
  "Staffel 34, Folge 20: Die kleinen Raupen Nimmersatt",
  "Staffel 34, Folge 21: Pädagogische Ansichten eines Clowns",
  "Staffel 34, Folge 22: Homers unglaubliche Reise durch die Windschutzscheibe",
  "Staffel 35, Folge 1: Schülerlotse Homer",
  "Staffel 35, Folge 2: Der Traum vom Erwachsenwerden",
  "Staffel 35, Folge 3: Lambo-Man",
  "Staffel 35, Folge 4: Entsalzt",
  "Staffel 35, Folge 5: Die Homer-Mutation",
  "Staffel 35, Folge 6: Ein Freund aus Townsburg",
  "Staffel 35, Folge 7: Unser kleines Farmhaus",
  "Staffel 35, Folge 8: Liebe unterm Schottenrock",
  "Staffel 35, Folge 9: Nerd ist ihr Hobby",
  "Staffel 35, Folge 10: Do the Wrong Thing",
  "Staffel 35, Folge 11: Frinkensteins Monster",
  "Staffel 35, Folge 12: Lisa bleibt auf der Strecke",
  "Staffel 35, Folge 13: Cave Mom",
  "Staffel 35, Folge 14: Ein Mops kam in die Küche",
  "Staffel 35, Folge 15: Fünf Amigos!",
  "Staffel 35, Folge 16: Diamantenfieber",
  "Staffel 35, Folge 17: Der Rest ist für Sie",
  "Staffel 35, Folge 18: Barts Gehirn"
];


const generateButton = document.getElementById("randomize");
const countSelect = document.getElementById("count");
const output = document.querySelector("p");

function generateRandomEpisodes() {
  const count = parseInt(countSelect.value);
  const chosen = [];

  while (chosen.length < count) {
    const randomIndex = Math.floor(Math.random() * words.length);
    const episode = words[randomIndex];
    if (!chosen.includes(episode)) {
      chosen.push(episode);
    }
  }

  let resultText = "";

  if (chosen.length === 1) {
  resultText = `<i>${chosen[0]}</i>`;
} else if (chosen.length === 2) {
  resultText = `<i>${chosen[0]}</i> und <br><i>${chosen[1]}</i>`;
} else if (chosen.length > 2) {
  const allButLast = chosen.slice(0, -1).map(ep => `<i>${ep}</i>`).join(", <br>");
  const last = `<i>${chosen[chosen.length - 1]}</i>`;
  resultText = `${allButLast} und <br>${last}`;
}

  output.innerHTML = ` ${resultText}`;
}

generateButton.addEventListener("click", generateRandomEpisodes);
